drop trigger carrecord;
drop trigger locationcard;
drop trigger staff;
drop trigger LED;
drop trigger staffrecord;
drop trigger carinfo;
drop trigger bstation;
drop trigger userworks;
drop trigger department;